name: mindful
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.2
  flutter_svg: ^2.2.1
  ionicons: ^0.2.2
  supabase_flutter: ^2.10.3
  supabase: ^2.10.0
  image_picker: ^1.2.1
  sign_in_with_apple: ^7.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Prime
      fonts:
        - asset: assets/fonts/Prime-Light.otf
        - asset: assets/fonts/Prime-Regular.otf
          style: italic
